<?php
/**********************************************************************
   
***********************************************************************/
$path_to_root = "../..";
include_once($path_to_root . "/includes/ui/payroll_emp_info_ui_lists.inc");
include_once($path_to_root . "/includes/ui/ui_controls.inc");
include_once($path_to_root . "/includes/ui/payroll_ui_input.inc");
include_once($path_to_root . "/includes/ui/ui_msgs.inc");
include_once($path_to_root . "/includes/ui/ui_globals.inc");
include_once($path_to_root . "/includes/ui/ui_view.inc");
include_once($path_to_root . "/includes/payroll_data_checks.inc");



?>